# Generated by Django 5.2.1 on 2025-10-13 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0022_deliverynote_scanned_barcodes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scale',
            name='scale_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the scale. Can be changed by an admin.', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='weighingrecord',
            name='weighing_scale_id',
            field=models.CharField(blank=True, help_text='The ID of the scale at the time of weighing.', max_length=100),
        ),
        migrations.CreateModel(
            name='ScaleIdHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('old_id', models.CharField(max_length=100)),
                ('new_id', models.CharField(max_length=100)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_history', to='scale.scale')),
            ],
            options={
                'ordering': ['-change_date'],
            },
        ),
    ]
