# Generated by Django 5.2.1 on 2025-09-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0022_deliverynote_scanned_barcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scale',
            name='decode_encoding',
            field=models.CharField(blank=True, help_text="Python codec name used to decode bytes, e.g. 'utf-8'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scale',
            name='decode_end_index',
            field=models.IntegerField(blank=True, help_text='End index for slicing decoded string (exclusive). Leave blank to go to end', null=True),
        ),
        migrations.AddField(
            model_name='scale',
            name='decode_start_index',
            field=models.IntegerField(blank=True, help_text='Start index for slicing decoded string (inclusive)', null=True),
        ),
        migrations.AddField(
            model_name='scale',
            name='decode_strip_chars',
            field=models.CharField(blank=True, help_text="Characters to strip from the decoded slice, e.g. ', \r\n' ", max_length=50, null=True),
        ),
    ]
