# Generated by Django 5.2.1 on 2025-10-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0023_scale_scale_id_weighingrecord_weighing_scale_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='scale_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the scale. Can be changed by an admin.', max_length=100, null=True, unique=True),
        ),
    ]
