# Generated by Django 5.2.1 on 2025-09-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0023_scale_decode_encoding_scale_decode_end_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scale',
            name='decode_preset',
            field=models.CharField(blank=True, choices=[('0:7', '[0:7]'), ('4:8', '[4:8]'), ('7:14', '[7:14]'), ('full', 'Full string')], help_text='Predefined slice for decoding the scale output', max_length=20, null=True),
        ),
    ]
