# Generated by Django 5.2.1 on 2025-09-29 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0024_scale_decode_preset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scale',
            name='decode_encoding',
        ),
        migrations.RemoveField(
            model_name='scale',
            name='decode_end_index',
        ),
        migrations.RemoveField(
            model_name='scale',
            name='decode_start_index',
        ),
        migrations.RemoveField(
            model_name='scale',
            name='decode_strip_chars',
        ),
    ]
