# Generated by Django 5.2.1 on 2025-10-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0024_alter_scale_scale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingprocess',
            name='allow_bale_insert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weighingprocess',
            name='allow_marshalling',
            field=models.BooleanField(default=False),
        ),
    ]
