# Generated by Django 5.2.1 on 2025-10-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0025_weighingprocess_allow_bale_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighingprocess',
            name='process_type',
            field=models.CharField(blank=True, choices=[('WeighBridge', 'WeighBridge'), ('Manual', 'Manual'), ('Automated', 'Automated'), ('ctl_workflow', 'CTL Workflow'), ('ctl_commercial_workflow', 'CTL Commercial Workflow')], default='WeighBridge', max_length=100, null=True),
        ),
    ]
