# Generated by Django 5.2.1 on 2025-11-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0026_alter_weighingprocess_process_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingprocess',
            name='allow_spaces_in_barcode',
            field=models.BooleanField(default=False, help_text='If enabled, spaces in barcodes will not be stripped (e.g. for Code 39 Mod 43)'),
        ),
    ]
