# Generated by Django 5.2.1 on 2025-11-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0027_weighingprocess_allow_spaces_in_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingprocess',
            name='use_code39_mod43_validation',
            field=models.BooleanField(default=False, help_text='If enabled, validates scanned barcodes using Code 39 Mod 43 algorithm.'),
        ),
    ]
