# Generated by Django 5.2.1 on 2025-12-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0028_weighingprocess_use_code39_mod43_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingprocess',
            name='rolling_hessian',
            field=models.BooleanField(default=False, help_text='If enabled, pre-populates the hessian value from the previous weighing record for the same delivery note.'),
        ),
    ]
