# Generated by Django 5.2.1 on 2025-12-11 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0029_weighingprocess_rolling_hessian'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grower_name', models.CharField(blank=True, max_length=100)),
                ('grower_number', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('scale_id', models.CharField(blank=True, max_length=100)),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tare_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(default='kg', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('printing_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='scale.printingnote')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scale.product')),
            ],
        ),
    ]
