# Generated by Django 5.2.1 on 2026-01-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0030_printingnote_printingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingnote',
            name='expected_bales',
            field=models.IntegerField(blank=True, help_text='Total expected number of barcodes/bales', null=True),
        ),
    ]
