# Generated by Django 5.2.1 on 2026-01-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0031_printingnote_expected_bales'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingrecord',
            name='moisture',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
