# Generated by Django 5.2.1 on 2026-02-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0032_printingrecord_moisture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingrecord',
            name='moisture',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
