# Generated by Django 5.2.1 on 2026-02-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0033_allow_null_moisture'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='target_endpoint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
