# Generated by Django 5.2.1 on 2026-02-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0034_companysettings_target_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingprocess',
            name='auto_save_on_scan',
            field=models.BooleanField(default=False, help_text='If enabled, scanning a barcode will automatically trigger a save.'),
        ),
    ]
