# Generated by Django 5.2.1 on 2026-02-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0034_companysettings_target_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='satellite',
            field=models.BooleanField(default=False),
        ),
    ]
