# Generated by Django 5.2.1 on 2026-02-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0035_weighingprocess_auto_save_on_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='satellite',
            field=models.BooleanField(default=False),
        ),
    ]
