# Generated by Django 5.2.1 on 2026-03-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0036_companysettings_satellite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scale',
            name='mettler_toledo',
            field=models.BooleanField(default=False, help_text='Enable scale connection that may help with Mettler Toledo scales'),
        ),
    ]
