# Generated by Django 5.2.1 on 2026-03-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0037_scale_mettler_toledo'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingprocess',
            name='rolling_grower_number',
            field=models.BooleanField(default=False, help_text='If enabled, pre-populates the grower number from the previous weighing record for the same delivery note.'),
        ),
    ]
