# Generated by Django 5.2.1 on 2026-03-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0038_weighingprocess_rolling_grower_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighingprocess',
            name='rolling_grower_number',
            field=models.BooleanField(default=False, help_text='If enabled, pre-populates the grower number from the previous weighing record for this process.'),
        ),
    ]
