# Generated by Django 5.2.1 on 2026-03-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0039_alter_weighingprocess_rolling_grower_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighingprocess',
            name='send_simple_request',
            field=models.BooleanField(default=False),
        ),
    ]
